/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
package com.kyee.iszx.bean;

/**
 * ky_application
 * 
 * @author zxx
 * @version 1.0.0 2019-12-11
 */
public class KyApplication implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -8126950008223151762L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 唯一主键 */
    private Integer appId;

    /** 应用名称 */
    private String appName;

    /** 应用编号 */
    private String appCode;

    /** 应用描述 */
    private String appDescription;

    /** 授权信息 */
    private String appAuthorize;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取唯一主键
     * 
     * @return 唯一主键
     */
    public Integer getAppId() {
        return this.appId;
    }

    /**
     * 设置唯一主键
     * 
     * @param appId
     *          唯一主键
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * 获取应用名称
     * 
     * @return 应用名称
     */
    public String getAppName() {
        return this.appName;
    }

    /**
     * 设置应用名称
     * 
     * @param appName
     *          应用名称
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * 获取应用编号
     * 
     * @return 应用编号
     */
    public String getAppCode() {
        return this.appCode;
    }

    /**
     * 设置应用编号
     * 
     * @param appCode
     *          应用编号
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * 获取应用描述
     * 
     * @return 应用描述
     */
    public String getAppDescription() {
        return this.appDescription;
    }

    /**
     * 设置应用描述
     * 
     * @param appDescription
     *          应用描述
     */
    public void setAppDescription(String appDescription) {
        this.appDescription = appDescription;
    }

    /**
     * 获取授权信息
     * 
     * @return 授权信息
     */
    public String getAppAuthorize() {
        return this.appAuthorize;
    }

    /**
     * 设置授权信息
     * 
     * @param appAuthorize
     *          授权信息
     */
    public void setAppAuthorize(String appAuthorize) {
        this.appAuthorize = appAuthorize;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}