package com.kyee.iszx.bean;

public class KyAppSetting implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -6032796199984932262L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 唯一id */
    private Integer id;

    /** 参数所属的appid */
    private Integer appId;

    /** 参数名称 */
    private String paramName;

    /** 参数值 */
    private String paramValue;

    /** 参数类型 */
    private String paramType;

    
    /** 参数描述*/
    private String description;
    
    /** 参数编码*/
    private String paramCode;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取唯一id
     * 
     * @return 唯一id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置唯一id
     * 
     * @param id
     *          唯一id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取参数所属的appid
     * 
     * @return 参数所属的appid
     */
    public Integer getAppId() {
        return this.appId;
    }

    /**
     * 设置参数所属的appid
     * 
     * @param appId
     *          参数所属的appid
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * 获取参数名称
     * 
     * @return 参数名称
     */
    public String getParamName() {
        return this.paramName;
    }

    /**
     * 设置参数名称
     * 
     * @param paramName
     *          参数名称
     */
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    /**
     * 获取参数值
     * 
     * @return 参数值
     */
    public String getParamValue() {
        return this.paramValue;
    }

    /**
     * 设置参数值
     * 
     * @param paramValue
     *          参数值
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * 获取参数类型
     * 
     * @return 参数类型
     */
    public String getParamType() {
        return this.paramType;
    }

    /**
     * 设置参数类型
     * 
     * @param paramType
     *          参数类型
     */
    public void setParamType(String paramType) {
        this.paramType = paramType;
    }

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getParamCode() {
		return paramCode;
	}

	public void setParamCode(String paramCode) {
		this.paramCode = paramCode;
	}

	
    /* This code was generated by TableGo tools, mark 2 end. */
}