/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
package com.kyee.iszx.bean;

/**
 * parameter_type
 * 
 * @author zxx
 * @version 1.0.0 2019-12-11
 */
public class ParameterType implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 5799180147147909702L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 逻辑主键 */
    private Integer id;

    /** 参数类型 */
    private String type;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取逻辑主键
     * 
     * @return 逻辑主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置逻辑主键
     * 
     * @param id
     *          逻辑主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取参数类型
     * 
     * @return 参数类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * 设置参数类型
     * 
     * @param type
     *          参数类型
     */
    public void setType(String type) {
        this.type = type;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}